export const EmailTemplateJoditConfig = {
  readonly: false,
  height: 400,
  toolbar: true,
  toolbarButtonSize: "middle" as const,

  buttons: [
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "|",
    "ul",
    "ol",
    "|",
    "font",
    "fontsize",
    "|",
    "align",
    "|",
    "undo",
    "redo",
    "|",
    "eraser",
  ],

  buttonsMD: ["bold", "italic", "underline", "ul", "ol", "undo", "redo"],
  buttonsSM: ["bold", "italic", "underline", "undo", "redo"],
  buttonsXS: ["bold", "italic", "underline"],

  disablePlugins: [
    "image",
    "file",
    "video",
    "media",
    "link",
    "pasteStorage",
    "iframe",
    "table",
    "source",
    "fullsize",
    "about",
    "print",
  ],

  showCharsCounter: false,
  showWordsCounter: false,
  showXPathInStatusbar: false,
  askBeforePasteHTML: false,
  askBeforePasteFromWord: false,
  defaultActionOnPaste: "insert_as_text" as const,
  allowResizeX: false,
  allowResizeY: false,
  statusbar: false,
  addNewLine: false,
};
